hack: bashate and doc8 from pip on rhos-11
This hack self-destructs once we get bashate and doc8
rpms published.

RCM-15611

Change-Id: I55d4a4948a38e5f2c7db51a60cbf019bd5b063e0

diff --git a/components_config/11/python-cinderclient/component.yml b/components_config/11/python-cinderclient/component.yml
--- a/components_config/11/python-cinderclient/component.yml
+++ b/components_config/11/python-cinderclient/component.yml
@@ -54,7 +54,7 @@ rpm_deps: [
   python-fixtures,
   python-subunit,
   python-pep8,
-  python-bashate,
+  # python-bashate,
 
   "{{ hostvars[inventory_hostname][tester.component.tox_target]['rpm_deps'] }}"
 ]
@@ -64,11 +64,15 @@ remove_rpm: [ "{{ hostvars[inventory_hostname][tester.component.tox_target]['rem
 
 # Common pre-run steps used by all tester types
 cinderclient_virt_run_config:
-  run: >
-    set -o pipefail;
-    rpm -qa | sort > ../logs/installed-rpms.log;
-    truncate --size 0 requirements.txt;
-    truncate --size 0 test-requirements.txt;
+  run: |
+    set -eo pipefail
+    rpm -qa | sort > ../logs/installed-rpms.log
+    truncate --size 0 requirements.txt
+    truncate --size 0 test-requirements.txt
+
+    sudo easy_install pip
+    sudo pip install bashate
+    if yum list -q python2-bashate 2>/dev/null; then echo 'ERROR: Time to remove `pip install bashate` hack from octario.'; exit 1; fi
 
     {{ hostvars[inventory_hostname][tester.component.tox_target]['run'] }}
 
