hack: bashate and doc8 from pip on rhos-11
This hack self-destructs once we get bashate and doc8
rpms published.

RCM-15611

Change-Id: I55d4a4948a38e5f2c7db51a60cbf019bd5b063e0

diff --git a/components_config/11/sahara/component.yml b/components_config/11/sahara/component.yml
--- a/components_config/11/sahara/component.yml
+++ b/components_config/11/sahara/component.yml
@@ -42,8 +42,8 @@ rpm_deps: [
   python-saharaclient,
 
   bandit,
-  python-bashate,
-  python-doc8,
+  # python-bashate,
+  # python-doc8,
   python-pygments,
   python-tempest-lib,
   python-testrepository,
@@ -59,20 +59,27 @@ remove_rpm: [ "{{ hostvars[inventory_hostname][tester.component.tox_target]['rem
 
 # Common pre-run steps used by all tester types
 sahara_virt_run_config:
-  run: >
-    set -o pipefail;
-    rpm -qa | sort > ../logs/installed-rpms.log;
+  run: |
+    set -eo pipefail
+    rpm -qa | sort > ../logs/installed-rpms.log
 
-    truncate --size 0 requirements.txt;
-    truncate --size 0 test-requirements.txt;
+    truncate --size 0 requirements.txt
+    truncate --size 0 test-requirements.txt
 
-    echo "WARN:	Patching source for keeping test coverage while not supporting all plugins from upstream in the release.";
-    sed -i'.bak' -e "/^version/d" setup.cfg;
-    sed -i'.bak' -e "/ambari/! { s/default=\[/default=\['ambari', /g;}" sahara/plugins/base.py;
-    sed -i'.bak' -e "/spark/! { s/default=\[/default=\['spark', /g;}" sahara/plugins/base.py;
-    sed -i'.bak' -e "/cdh/! { s/default=\[/default=\['cdh', /g;}" sahara/plugins/base.py;
-    sed -i'.bak' -e "/vanilla/! { s/default=\[/default=\['vanilla', /g;}" sahara/plugins/base.py;
-    sed -i'.bak' -e "/hdp/! { s/default=\[/default=\['hdp', /g;}" sahara/plugins/base.py;
+    echo "WARN:	Patching source for keeping test coverage while not supporting all plugins from upstream in the release."
+    sed -i'.bak' -e "/^version/d" setup.cfg
+    sed -i'.bak' -e "/ambari/! { s/default=\[/default=\['ambari', /g;}" sahara/plugins/base.py
+    sed -i'.bak' -e "/spark/! { s/default=\[/default=\['spark', /g;}" sahara/plugins/base.py
+    sed -i'.bak' -e "/cdh/! { s/default=\[/default=\['cdh', /g;}" sahara/plugins/base.py
+    sed -i'.bak' -e "/vanilla/! { s/default=\[/default=\['vanilla', /g;}" sahara/plugins/base.py
+    sed -i'.bak' -e "/hdp/! { s/default=\[/default=\['hdp', /g;}" sahara/plugins/base.py
+
+    sudo easy_install pip
+    sudo pip install bashate
+    if yum list -q python-bashate 2>/dev/null; then echo 'ERROR: Time to remove `pip install bashate` hack from octario.'; exit 1; fi
+
+    sudo pip install doc8
+    if yum list -q python-doc8 2>/dev/null; then echo 'ERROR: Time to remove `pip install doc8` hack from octario.'; exit 1; fi
 
     {{ hostvars[inventory_hostname][tester.component.tox_target]['run'] }}
 
